version: '3.1'
services:

  redmine:
    image: redmine:4.0-passenger
    container_name: redmine-appserver
    ports:
      - "6080:3000"
    hostname: redmine-appserver
    depends_on:
      - mysql
      - mailhog
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_ENCODING: utf8
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_DATABASE: redmine
      REDMINE_PLUGINS_MIGRATE: 1
    env_file: .env
    volumes:
      # Config directories.
      - ./data/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./data/manifest.js:/usr/src/redmine/app/assets/config/manifest.js
      # Other directories.
      - ./data/files:/usr/src/redmine/files
      - ./data/plugins:/usr/src/redmine/plugins
      - ./data/backups:/usr/src/redmine/backups
      - ./data/plugins/toggl2redmine/db/seeds.rb:/usr/src/redmine/db/seeds.rb

  mysql:
    image: mysql:5.7
    container_name: redmine-mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: redmine-mailhog
    hostname: mailhog
    ports:
      - "6825:8025"
      - "6125:1025"
